- hosts: localhost
  gather_facts: False
  vars_files:
    - ./reference.yml

  tasks:
    - name: create a key-pair
      ec2_key:
        name: "{{key_pair_name}}"
        region: us-east-2
      register: keyout

    - name: save key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: "./{{key_pair_name}}.pem"
      when: keyout.changed == True

    - name: create ec2 instance
      ec2_instance:
        key_name: "{{key_pair_name}}"
        name: "{{item.name}}"
        instance_type: t2.micro
        security_group: "{{sg_name}}"
        image_id: "{{item.id}}"
        region: us-east-2
        wait: yes
        exact_count: 1
        network:
          assign_public_ip: yes
      with_items: "{{machinename}}"
